TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += dbExampleDB.db
 DB += ioLogik_E1210.db
 DB += ioLogik_E1240.db
 DB += ioLogik_E1262.db
# DB += ioLogik_E1241.db
# DB += ioLogik_E1241-addons.db
 DB += ioLogik_E1242.db
 DB += ioLogik_E1242-addons.db
# DB += ioLogik_E1214.db
# DB += ioLogik_E1214-addons.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

